# Generated by Django 6.0.3 on 2026-03-27 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_type', models.CharField(choices=[('DB_ONLY', 'Database Only'), ('MEDIA_ONLY', 'Uploaded Files Only'), ('FULL', 'Full System (DB + Media)')], default='FULL', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Waiting to Start'), ('IN_PROGRESS', 'Currently Backing Up...'), ('COMPLETED', 'Backup Successful'), ('FAILED', 'Backup Failed')], default='PENDING', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='secure_backups/%Y/%m/')),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_backups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
